#pragma once

#ifndef PYMEMTOOLS_PYTHON_VERSION
#define PYMEMTOOLS_PYTHON_VERSION 310
#endif

#if (PYMEMTOOLS_PYTHON_VERSION != 310) && (PYMEMTOOLS_PYTHON_VERSION != 314)
#error "Unsupported PYMEMTOOLS_PYTHON_VERSION (use 310 or 314)"
#endif
